### PR TITLE
Add Gherkin support

### PR DESCRIPTION
**Pull request by FF-Brown**
Add support for Gherkin feature files

### CODE REVIEW

**Comment by reduckted** [comment]
Fantastic, thank you!

**Comment by FF-Brown** [comment]
@reduckted Will this show up as an update in Visual Studio?
(I saw you made a new release)

**Comment by reduckted** [comment]
Yes, 1.6.0 is on the marketplace now (it's automatically published when a new release is created in GitHub) and should appear as an update in Visual Studio.

**Comment by FF-Brown** [comment]
That's awesome, thank you!

**Pull request merged**
